## Tensors

- Tensors are a specialized data structure that are very similar to arrays and matrices. 
- In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.
- Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. 
- In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.
- Tensors are also optimized for automatic differentiation

In [2]:
import torch
import numpy as np

### Initializing a Tensor

Tensors can be created directly from data. The data type is automatically inferred.

Using torch.tensor() is the most straightforward way to create a tensor if you already have data in a Python tuple or list. As shown above, nesting the collections will result in a multi-dimensional tensor.

torch.tensor() creates a copy of the data.

In [9]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [10]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [17]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


### Tensors and numpy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [18]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [19]:
# Tensor to NumPy array

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [20]:
# A change in the tensor reflects in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [21]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2332, 0.4047],
        [0.2162, 0.9927]]) 



### CPU and GPU
By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). 

Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [23]:
# We move our tensor to the GPU, if available
if torch.backends.mps.is_available():
    tensor = x_rand.to("mps")
    print("data stored in gpu")

# Types of devices -- 
# cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mps, xla, lazy, vulkan, meta, hpu, privateuseone


data stored in gpu


### Reproducibility

Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.

**https://pytorch.org/docs/stable/notes/randomness.html**